apiVersion: v1
kind: Pod
metadata:
  name: crawler
  labels:
    name: crawler
spec:
  containers:
  - name: crawler
    image: tonyq2k3/reddit-crawler:0.3
    # imagePullPolicy: Always
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
    - name: BOOTSTRAP_SERVERS
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: IP_KAFKA_BROKER
    - name: USER
      valueFrom:
        secretKeyRef:
          name: crawler-secret
          key: USER
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: crawler-secret
          key: PASSWORD
    - name: CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: crawler-secret
          key: CLIENT_ID
    - name: CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: crawler-secret
          key: CLIENT_SECRET
    - name: USER_AGENT
      valueFrom:
        secretKeyRef:
          name: crawler-secret
          key: USER_AGENT
