apiVersion: v1
kind: Pod
metadata:
  name: submitter
  labels:
    name: submitter
spec:
  containers:
  - name: submitter
    image: tonyq2k3/task-submitter:0.3
    imagePullPolicy: Never
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
    - name: MONGO_URI
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: MONGO_URI
    - name: BOOTSTRAP_SERVERS
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: IP_KAFKA_BROKER
    - name: SPARK_MASTER
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: IP_SPARK_MASTER
    # restartPolicy: Never

