apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app: sentiment-analysis
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly9hZG1pbjowMTEyMjAwM0BjbHVzdGVyMC5hdGJvY3h5Lm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1DbHVzdGVyMA==
type: Opaque